apiVersion: v1
kind: Service
metadata:
    name: grpc-client-service
spec:
    type: ClusterIP
    selector:
        app: grpc-client
    ports:
        - port: 8082
          protocol: TCP
          targetPort: 8082
